/*
 * Stage 1 of the driver-to-task assignment engine (see project chat for the full spec).
 *
 * Different job from order_b_engine.js/joint_scheduler.js: those *generate* trips/tasks from a
 * raw Order B file. This engine assumes the tasks already exist, in two files a supervisor
 * already has:
 *   - a Roster (Control Staff) workbook: one row per driver, one column per day of the month,
 *     each day cell either blank (available), a leave/absence code (F/O/V/VR/A0/... or a
 *     training code like "830/7T"), or (once assigned) a task code.
 *   - a Task Program workbook: one sheet per day, one row per task slot, with a "Tasks" (task
 *     code) column and a "NAME" column that's blank/unresolved until a driver is assigned.
 *
 * The job here is purely the assignment + write-back loop a supervisor currently does by hand:
 * pick an available driver for each task, write their name onto the task, and write the task
 * code back onto their roster day -- nothing about *which* driver is generated by any of the
 * order_b_engine trip-matching logic, since these tasks are already fully formed.
 *
 * Both workbooks are read and written with ExcelJS so every existing style/merge/formula that
 * isn't touched survives untouched -- the two output files must look exactly like the input
 * files except for the specific cells this engine fills in.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.DriverAssignmentEngine = factory();
  }
})(typeof self !== "undefined" ? self : this, function () {

  function dateKey(d) {
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  }

  function addDays(date, n) {
    const d = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    d.setDate(d.getDate() + n);
    return d;
  }

  // Any non-blank cell -- a leave code, a training code, or an already-assigned task code --
  // means that driver isn't free to take on new work that day.
  function isAvailable(status) {
    return status == null || String(status).trim() === "";
  }

  // The roster's identity/header columns (STAFF, ID, CATEGORY, Phone, and the date headers) are
  // themselves formulas pulling from an external "JAN" master sheet in a different workbook --
  // ExcelJS gives back {formula, result} for those instead of a plain value. Day-status cells
  // (F/V/O/a task code/...) are already plain literals, so this is a no-op for them. A cached
  // date-formula result also comes back as an ISO string rather than a real Date, so this
  // normalizes that too, since date detection elsewhere expects a Date instance.
  function displayValue(cell) {
    let v = cell.value;
    if (v && typeof v === "object" && !(v instanceof Date) && "result" in v) {
      v = v.result;
      if (v && typeof v === "object" && "error" in v) return null; // e.g. unresolved VLOOKUP -> #N/A
    }
    if (typeof v === "string" && /^\d{4}-\d{2}-\d{2}T/.test(v)) {
      const d = new Date(v);
      if (!isNaN(d.getTime())) return d;
    }
    return v;
  }

  // "R" anywhere in the letters after the duration means Reserve (however many letters follow --
  // R/RB/RK/RA/... are all still Reserve, the letter is a station/sequence detail we don't need
  // to interpret). "S" (and no "R") means Sweep, the track-inspection run. Anything else is a
  // real trip.
  function classifyCode(code) {
    const m = /^(\d{3,4})\/(\d{1,2})([A-Za-z]{1,3})\s*$/.exec(String(code).trim());
    if (!m) return "trip";
    const suffix = m[3].toUpperCase();
    if (suffix.includes("R")) return "reserve";
    if (suffix.includes("S")) return "sweep";
    return "trip";
  }

  // The first letter of a trip code's suffix names its destination -- confirmed directly by the
  // supervisor: L = MAK (Makkah), A = KAIA (the airport), M = MAD (Madinah). Only meaningful for
  // "trip" kind codes (reserve/sweep codes use R/S for that same position to mean something
  // else entirely, handled by classifyCode above).
  function classifyDestination(code) {
    const m = /^(\d{3,4})\/(\d{1,2})([A-Za-z]{1,3})\s*$/.exec(String(code).trim());
    if (!m) return null;
    const first = m[3][0].toUpperCase();
    if (first === "L") return "MAK";
    if (first === "A") return "KAIA";
    if (first === "M") return "MAD";
    return null;
  }

  // A task's cell being highlighted yellow in the Task Program is how the supervisor marks that
  // specific leg as a Passenger assignment (as opposed to Main/driving) -- confirmed directly.
  function isPassengerLegCell(cell) {
    const fill = cell.fill;
    if (!fill || fill.type !== "pattern" || fill.pattern !== "solid") return false;
    const argb = fill.fgColor && fill.fgColor.argb;
    return typeof argb === "string" && argb.toUpperCase().endsWith("FFFF00");
  }

  // Finds a header row by scanning for an exact (case-insensitive) label match rather than
  // assuming fixed row/column numbers -- the real files aren't guaranteed to keep the same
  // layout from month to month, only the same labels.
  function findHeaderCell(ws, label, maxScanRow) {
    const target = label.trim().toUpperCase();
    for (let r = 1; r <= maxScanRow; r++) {
      const row = ws.getRow(r);
      for (let c = 1; c <= ws.columnCount; c++) {
        const v = displayValue(row.getCell(c));
        if (typeof v === "string" && v.trim().toUpperCase() === target) {
          return { row: r, col: c };
        }
      }
    }
    return null;
  }

  // --- Roster (Control Staff) parsing ------------------------------------------------------
  function parseRoster(workbook) {
    const ws = workbook.worksheets[0];
    const staffCell = findHeaderCell(ws, "STAFF", 15);
    if (!staffCell) throw new Error("Could not find the roster's \"STAFF\" header -- is this a Control Staff roster file?");
    const idCell = findHeaderCell(ws, "ID", 15);
    const phoneCell = findHeaderCell(ws, "Phone", 15);
    const categoryCell = findHeaderCell(ws, "CATEGORY", 15);

    const headerRow = staffCell.row;
    const staffCol = staffCell.col;
    const headerRowObj = ws.getRow(headerRow);
    const dateCols = [];
    for (let c = staffCol + 1; c <= ws.columnCount; c++) {
      const v = displayValue(headerRowObj.getCell(c));
      if (v instanceof Date) dateCols.push({ col: c, date: v, key: dateKey(v) });
    }
    if (!dateCols.length) throw new Error("Could not find any date columns on the roster's header row.");

    const drivers = [];
    for (let r = headerRow + 1; r <= ws.rowCount; r++) {
      const row = ws.getRow(r);
      const staffVal = displayValue(row.getCell(staffCol));
      // Real driver rows are "<ID>-<NAME>" (trainees show as "T- <ID>-<NAME>"); the
      // footer/summary block below the driver list doesn't match this shape, which is how we
      // know to stop without hardcoding a row number.
      if (typeof staffVal !== "string" || !staffVal.includes("-")) continue;
      const idValRaw = idCell ? displayValue(row.getCell(idCell.col)) : null;
      // Strip everything but digits -- a stray invisible character or trailing space in the ID
      // cell (seen in real data) would otherwise silently drop that driver from the roster.
      const idDigits = idValRaw == null ? "" : String(idValRaw).replace(/[^\d]/g, "");
      if (!/^\d{5,8}$/.test(idDigits)) continue;

      // Locate the ID inside the STAFF text itself (rather than just splitting on the first
      // dash) so a "T- " trainee prefix doesn't get swallowed into the name -- and keep whatever
      // that prefix literally was (namePrefix), so a written-back task assignment can reproduce
      // it exactly rather than assuming every file spells it "T- ".
      const idPosInStaff = staffVal.indexOf(idDigits);
      const namePrefix = idPosInStaff >= 0 ? staffVal.slice(0, idPosInStaff) : "";
      const name = idPosInStaff >= 0
        ? staffVal.slice(idPosInStaff + idDigits.length).replace(/^[\s-]+/, "").trim()
        : staffVal.slice(staffVal.indexOf("-") + 1).trim();
      const phoneVal = phoneCell ? displayValue(row.getCell(phoneCell.col)) : null;
      const categoryVal = categoryCell ? displayValue(row.getCell(categoryCell.col)) : null;

      const statusByDateKey = {};
      const colByDateKey = {};
      dateCols.forEach(({ col, key }) => {
        statusByDateKey[key] = displayValue(row.getCell(col));
        colByDateKey[key] = col;
      });

      drivers.push({
        id: idDigits,
        name,
        namePrefix,
        phone: phoneVal != null ? String(phoneVal).trim() : "",
        category: categoryVal != null ? String(categoryVal).trim() : "",
        row: r,
        statusByDateKey,
        colByDateKey,
      });
    }
    if (!drivers.length) throw new Error("Found the roster's header row but no driver rows underneath it.");

    return { sheetName: ws.name, headerRow, staffCol, dateKeys: dateCols.map((d) => d.key), drivers };
  }

  // Time-of-day cells (Start/End) load as native Date objects anchored to an arbitrary epoch
  // (Excel's own "time-only" serial-date convention) -- only the hour/minute portion means
  // anything, and it's UTC because that's how ExcelJS parses the underlying serial number.
  function timeCellToMinutes(v) {
    return v instanceof Date ? v.getUTCHours() * 60 + v.getUTCMinutes() : null;
  }

  // --- Task Program parsing -----------------------------------------------------------------
  // One tab per day. The file's own date cells are inconsistent test placeholders (confirmed
  // with the supervisor) -- the authoritative date for each tab is startDate + its position in
  // the workbook, which is also why the supervisor sets the schedule's start date before
  // dropping files, rather than this engine trying to read a date out of the sheet.
  function parseTaskProgram(workbook, startDate) {
    const days = [];
    workbook.worksheets.forEach((ws, idx) => {
      const tasksCell = findHeaderCell(ws, "Tasks", 15);
      if (!tasksCell) return; // sheet doesn't look like a task-program day -- skip it
      const nameCell = findHeaderCell(ws, "NAME", 15);
      if (!nameCell) throw new Error(`Sheet "${ws.name}" has a "Tasks" column but no "NAME" column next to it.`);
      const startCell = findHeaderCell(ws, "Start", 15);
      const endCell = findHeaderCell(ws, "End", 15);

      const date = addDays(startDate, idx);
      const tasks = [];
      for (let r = tasksCell.row + 1; r <= ws.rowCount; r++) {
        const taskCell = ws.getRow(r).getCell(tasksCell.col);
        const raw = displayValue(taskCell);
        const code = typeof raw === "string" ? raw.trim() : null;
        if (code && /^\d{3,4}\/\d{1,2}[A-Za-z]{1,3}$/.test(code)) {
          const startMin = startCell ? timeCellToMinutes(displayValue(ws.getRow(r).getCell(startCell.col))) : null;
          const endMin = endCell ? timeCellToMinutes(displayValue(ws.getRow(r).getCell(endCell.col))) : null;
          tasks.push({
            row: r, code, kind: classifyCode(code), destination: classifyDestination(code),
            startMin, endMin, isPassengerLeg: isPassengerLegCell(taskCell),
          });
        }
      }
      days.push({
        sheetIndex: idx, sheetName: ws.name, date, dateKey: dateKey(date),
        taskCol: tasksCell.col, nameCol: nameCell.col, tasks,
      });
    });
    return days;
  }

  function shuffle(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }

  // Stage 1 baseline: for each day, randomly pair available drivers with that day's task slots,
  // one each, no double-booking. No ratio/shift-lock/rest-time reasoning yet -- that's Stage 2's
  // job, layered on top of this same read/parse/write foundation once it's proven solid.
  function assignSimple(rosterData, taskDays) {
    const perDay = taskDays.map((day) => {
      const available = shuffle(rosterData.drivers.filter((d) => isAvailable(d.statusByDateKey[day.dateKey])));
      const n = Math.min(available.length, day.tasks.length);
      const assignments = [];
      for (let i = 0; i < n; i++) {
        assignments.push({ task: day.tasks[i], driver: available[i] });
      }
      return {
        date: day.date, dateKey: day.dateKey, sheetIndex: day.sheetIndex, nameCol: day.nameCol,
        assignments,
        unassignedTasks: day.tasks.slice(n),
        unassignedDrivers: available.slice(n),
      };
    });
    return { perDay };
  }

  // --- Stage 2: shift-lock rotation, soft ratio balancing, hard rest-time -------------------
  // Everything below builds on the exact same parse/plan/patch shape as Stage 1 -- assignWithConditions()
  // returns the identical {perDay: [{assignments, unassignedTasks, unassignedDrivers, ...}]} shape
  // assignSimple() does, just with a smarter selection than "shuffle and take the first N".

  const SHIFT_NAMES = ["Early Morning", "Late Morning", "Early Afternoon", "Late Afternoon", "Night"];

  function defaultConditions() {
    return {
      // Blank on purpose -- the supervisor has to set every shift's window before Generate is
      // allowed to run, per how this was specified: "before we hit generate, we have to set
      // conditions."
      shifts: SHIFT_NAMES.map((name) => ({ name, start: "", end: "" })),
      ratioReserveDays: 4,
      ratioTripDays: 2,
      restHours: 12,
      shiftLockWeeks: 2,
    };
  }

  function parseHHMM(str) {
    const m = /^(\d{1,2}):(\d{2})$/.exec(String(str || "").trim());
    if (!m) return null;
    const h = parseInt(m[1], 10), mm = parseInt(m[2], 10);
    if (h > 23 || mm > 59) return null;
    return h * 60 + mm;
  }

  function conditionsAreComplete(conditions) {
    if (!conditions) return false;
    const shiftsOk = conditions.shifts.length === SHIFT_NAMES.length
      && conditions.shifts.every((s) => parseHHMM(s.start) != null && parseHHMM(s.end) != null);
    return shiftsOk
      && Number.isFinite(conditions.ratioReserveDays) && conditions.ratioReserveDays >= 0
      && Number.isFinite(conditions.ratioTripDays) && conditions.ratioTripDays >= 0
      && (conditions.ratioReserveDays + conditions.ratioTripDays) > 0
      && Number.isFinite(conditions.restHours) && conditions.restHours >= 0
      && Number.isInteger(conditions.shiftLockWeeks) && conditions.shiftLockWeeks >= 1;
  }

  // Handles a shift window that crosses midnight (e.g. Night 19:00-03:30) the same way a plain
  // one does (e.g. Early Morning 03:30-08:00) -- just two different comparisons depending on
  // which side of midnight the window falls on.
  function minutesInWindow(minutes, startMin, endMin) {
    if (startMin === endMin) return true;
    if (startMin < endMin) return minutes >= startMin && minutes < endMin;
    return minutes >= startMin || minutes < endMin;
  }

  // Circular distance (in minutes, around a 1440-minute day) between two times of day.
  function circularMinuteDist(a, b) {
    const d = Math.abs(a - b) % 1440;
    return Math.min(d, 1440 - d);
  }

  // A task's start time doesn't have to fall inside a configured shift's window to belong to
  // that shift -- if every window is exact and a task starts in a genuine gap between two of
  // them (e.g. a 03:00 task when the earliest shift opens at 03:30), it's assigned to whichever
  // shift's window it's nearest to in clock time, by policy: "consider that the closest shift."
  // An exact window match always wins outright; only a task in a true gap falls back to nearest.
  function classifyShiftForMinutes(conditions, minutes) {
    if (minutes == null) return null;
    let bestIdx = null, bestDist = Infinity;
    for (let i = 0; i < conditions.shifts.length; i++) {
      const s = conditions.shifts[i];
      const startMin = parseHHMM(s.start), endMin = parseHHMM(s.end);
      if (startMin == null || endMin == null) continue;
      if (minutesInWindow(minutes, startMin, endMin)) return i;
      const dist = Math.min(circularMinuteDist(minutes, startMin), circularMinuteDist(minutes, endMin));
      if (dist < bestDist) { bestDist = dist; bestIdx = i; }
    }
    return bestIdx;
  }

  // A driver's locked shift for a given date is computed purely from an anchor point (the date
  // and shift index they were locked into at some point) plus how many whole shiftLockWeeks
  // blocks have elapsed since then, cycling through the fixed Early Morning -> Late Morning ->
  // Early Afternoon -> Late Afternoon -> Night -> repeat order. Computing it this way (rather
  // than storing "current shift" directly) is what lets a later run just keep advancing from
  // wherever a previous run left off, without needing to replay every day in between.
  function computeShiftIndexForDriver(driverState, conditions, date) {
    if (!driverState || !driverState.shiftAnchorDate) return null;
    const anchor = new Date(driverState.shiftAnchorDate + "T00:00:00");
    const target = new Date(dateKey(date) + "T00:00:00");
    const daysBetween = Math.round((target - anchor) / 86400000);
    const weeksElapsed = Math.floor(daysBetween / 7);
    const blocksElapsed = Math.floor(weeksElapsed / conditions.shiftLockWeeks);
    const n = conditions.shifts.length;
    return ((driverState.shiftAnchorIndex + blocksElapsed) % n + n) % n;
  }

  // Circular distance between two shift indexes around the fixed 5-shift rotation order, used
  // only to rank fallback candidates (never a hard filter).
  function shiftDistance(a, b, cycleLen) {
    if (a == null) return cycleLen;
    const diff = Math.abs(a - b);
    return Math.min(diff, cycleLen - diff);
  }

  function minutesBetween(dateKeyA, minA, dateKeyB, minB) {
    const dA = new Date(dateKeyA + "T00:00:00");
    const dB = new Date(dateKeyB + "T00:00:00");
    return Math.round((dB - dA) / 60000) - minA + minB;
  }

  // How much a driver is "owed" of a given kind (reserve vs trip) relative to the configured
  // ratio -- a positive number means they've been getting less of that kind than the target
  // ratio calls for, so they're preferred for it. Judged against CUMULATIVE counts (every trip
  // and reserve this driver has ever had in this rotationState, not just a short rolling window)
  // -- a rolling window only ever prevents short-term streaks, it can't correct an imbalance that
  // built up earlier in the month, which is exactly what real monthly totals showed: some drivers
  // at 1 trip / 7 reserve, others at 10 trips / 1 reserve, despite the rolling-window rules never
  // being individually violated at any single point in time. This is still the "soft rule"
  // version: a preference used to sort candidates, never a hard filter, so it can't itself cause
  // a task to go unfilled the way the rest-time check can.
  // targetReserveFrac: the reserve share to compare this driver against -- see
  // groupReserveFrac() in assignWithConditions for where this actually comes from (each
  // driver's own shift-peer group's real running average, not a fixed configured number).
  function ratioPreference(driverState, targetReserveFrac, wantKind) {
    const totalReserve = driverState.cumulativeReserve || 0;
    const totalTrip = driverState.cumulativeTrip || 0;
    const total = totalReserve + totalTrip;
    if (!total) return 0;
    const targetFrac = wantKind === "reserve" ? targetReserveFrac : 1 - targetReserveFrac;
    const actualFrac = (wantKind === "reserve" ? totalReserve : totalTrip) / total;
    return targetFrac - actualFrac;
  }

  // ratioPreference alone is a pure sort-order nudge -- it can never by itself stop a driver from
  // drifting far past their fair share while someone else falls far behind. Originally this
  // measured "fair share" against the configured ratio (e.g. 3 reserve : 3 trip) directly. That
  // broke down against a real month's data: real task supply skewed heavily toward reserve (more
  // reserve slots than trip slots, plus every leftover available driver getting a manufactured
  // reserve duty), so a fixed 50/50 target became mathematically unreachable for most of the
  // roster partway through the month -- and once "everyone's already over" for a whole shift's
  // peer group, the old fallback just gave up on fairness entirely, letting the spread run wild
  // (some drivers over 90% reserve, others barely touched). Comparing each driver to their own
  // shift-peer group's actual running average instead of the fixed target keeps "fair" always
  // achievable no matter how skewed the real supply is: everyone within a shift group converges
  // toward the SAME ratio as their peers, rather than a random few absorbing the group's
  // shortfall alone. See groupReserveFrac() in assignWithConditions for where targetReserveFrac
  // comes from.
  const RATIO_TOLERANCE_DAYS = 1;
  function isOverKindQuota(driverState, targetReserveFrac, wantKind) {
    const totalReserve = driverState.cumulativeReserve || 0;
    const totalTrip = driverState.cumulativeTrip || 0;
    const total = totalReserve + totalTrip;
    if (!total) return false;
    const targetFrac = wantKind === "reserve" ? targetReserveFrac : 1 - targetReserveFrac;
    const fairShare = total * targetFrac;
    const count = wantKind === "reserve" ? totalReserve : totalTrip;
    return count >= fairShare + RATIO_TOLERANCE_DAYS;
  }

  // Staying within the ratio's total count isn't enough on its own -- a driver can still hit
  // exactly 3 reserve / 3 trip while every reserve day comes first and every trip day comes
  // last (RRRTTT). Explicit policy: "make it a mix, one day reserve one day trip... do not put
  // it in a sequence." A driver whose most recent assignment was already this same kind is
  // excluded from candidacy for another one of that kind, the same "unless it would empty the
  // list" pattern as the quota check -- this is what actually forces alternation (RTRTRT)
  // instead of just capping the total.
  function isRepeatingLastKind(driverState, wantKind) {
    const kinds = driverState.recentKinds || [];
    if (!kinds.length) return false;
    return kinds[kinds.length - 1] === wantKind;
  }

  // rotationState: { [driverId]: { shiftAnchorDate, shiftAnchorIndex, lastDutyEndDateKey,
  // lastDutyEndMin, recentKinds: [] } } -- passed in and mutated in place so the caller can
  // persist it (e.g. to localStorage per station) and hand it back in on the next run to
  // continue every driver's rotation/rest-time/ratio history instead of restarting cold.
  // specialRules (optional): per-driver overrides layered on top of the general rules, e.g. a
  // named driver who should never take a sweep, or should be steered toward/away from trips to
  // a particular destination. Each entry: { match(driver) => bool, excludeKinds: [...],
  // tripDestinationBias: {KAIA:n, MAK:n, MAD:n}, passengerLegBonus: {KAIA:n, MAK:n, MAD:n} }.
  // excludeKinds is a hard filter (that driver is never even a candidate for that task kind);
  // the bias fields are soft nudges added to the normal ratio-preference sort score, so they
  // steer selection without ever overriding the hard rest-time rule or leaving a task unfilled
  // when this driver was the only option.
  function isExcludedBySpecialRule(driver, task, specialRules) {
    return specialRules.some((rule) => rule.match(driver) && rule.excludeKinds && rule.excludeKinds.includes(task.kind));
  }
  function specialRuleBias(driver, task, specialRules) {
    if (task.kind !== "trip" || !task.destination) return 0;
    let bias = 0;
    specialRules.forEach((rule) => {
      if (!rule.match(driver)) return;
      if (rule.tripDestinationBias) bias += rule.tripDestinationBias[task.destination] || 0;
      if (task.isPassengerLeg && rule.passengerLegBonus) bias += rule.passengerLegBonus[task.destination] || 0;
    });
    return bias;
  }

  // When several reserve tasks share the exact same start time, filling all of them stacks
  // redundant standby coverage at one moment while a distinct, later reserve slot can go
  // completely uncovered with no driver at all -- reported directly against a real day, twice:
  // first two drivers both sitting reserve at the same time while late-shift slots showed no
  // name, then (after a first attempt at this fix that only separated "first at a time" from
  // "any repeat") three consecutive reserve slots at 09:00 all filled while slots at 12:00 and
  // 13:00 that ALSO had duplicates went empty -- because every duplicate, regardless of which
  // time it belonged to, was still being tried in plain chronological order, so an early time's
  // 2nd or 3rd slot could exhaust the driver pool before a later time's 2nd slot ever got a turn.
  // The actual fix has to be a round-robin by depth, not just a two-tier split: rank every
  // reserve task by its position among same-time siblings (1st, 2nd, 3rd, ...), then process
  // every time's 1st slot (in time order) before any time's 2nd slot, every 2nd before any 3rd,
  // and so on. That's what guarantees a distinct time's first shot at coverage always outranks
  // a DIFFERENT time's second-or-later slot, no matter how early or late either time falls in
  // the day. Only reordering; every task is still attempted exactly once.
  function spreadReserveTasks(reserveTasks) {
    const byStartMin = {};
    reserveTasks.forEach((t) => { (byStartMin[t.startMin] = byStartMin[t.startMin] || []).push(t); });
    // Object keys that look like non-negative integers (every startMin here) always iterate in
    // ascending numeric order in JS, regardless of insertion order -- this naturally walks times
    // chronologically without needing an explicit sort.
    const times = Object.keys(byStartMin);
    const maxDepth = Math.max(0, ...times.map((t) => byStartMin[t].length));
    const result = [];
    for (let depth = 0; depth < maxDepth; depth++) {
      times.forEach((t) => {
        if (byStartMin[t][depth]) result.push(byStartMin[t][depth]);
      });
    }
    return result;
  }

  function assignWithConditions(rosterData, taskDays, conditions, rotationState, specialRules) {
    const state = rotationState || {};
    const rules = specialRules || [];
    const cycleLen = conditions.shifts.length;
    const perDay = taskDays.map((day) => {
      const available = rosterData.drivers.filter((d) => isAvailable(d.statusByDateKey[day.dateKey]));

      // A driver seen for the first time (no rotation state yet, in this run or a previous one)
      // gets spread across the 5 shifts by their position in today's available list, rather than
      // everyone defaulting to the same shift.
      available.forEach((d, i) => {
        if (!state[d.id]) {
          state[d.id] = {
            shiftAnchorDate: day.dateKey, shiftAnchorIndex: i % cycleLen,
            lastDutyEndDateKey: null, lastDutyEndMin: null, recentKinds: [],
            cumulativeReserve: 0, cumulativeTrip: 0,
          };
        }
      });

      const byShift = {};
      const driverShiftIdx = {};
      available.forEach((d) => {
        const idx = computeShiftIndexForDriver(state[d.id], conditions, day.date);
        driverShiftIdx[d.id] = idx;
        (byShift[idx] = byShift[idx] || []).push(d);
      });

      // Each shift's peer-group reserve share, as of the start of today: the real running
      // average of everyone currently locked to that shift, not the configured ratio. Computed
      // once per day (not re-derived mid-day) so today's own picks don't shift the target out
      // from under each other. Falls back to the configured ratio only while a group has no
      // history at all yet (day 1, or a shift nobody's been locked to before).
      const configuredReserveFrac = conditions.ratioReserveDays / (conditions.ratioReserveDays + conditions.ratioTripDays);
      const groupTotals = {};
      Object.keys(byShift).forEach((idxStr) => {
        const idx = parseInt(idxStr, 10);
        const totals = { reserve: 0, trip: 0 };
        byShift[idx].forEach((d) => {
          const st = state[d.id];
          totals.reserve += st.cumulativeReserve || 0;
          totals.trip += st.cumulativeTrip || 0;
        });
        groupTotals[idx] = totals;
      });
      const groupReserveFrac = (idx) => {
        const totals = idx != null ? groupTotals[idx] : null;
        const groupTotal = totals ? totals.reserve + totals.trip : 0;
        return groupTotal ? totals.reserve / groupTotal : configuredReserveFrac;
      };

      const usedDriverIds = new Set();
      const assignments = [];
      const unassignedTasks = [];
      const capLen = conditions.ratioReserveDays + conditions.ratioTripDays;

      const restFilter = (list, task) => list.filter((d) => {
        if (isExcludedBySpecialRule(d, task, rules)) return false;
        const st = state[d.id];
        if (st.lastDutyEndMin == null) return true;
        const gap = minutesBetween(st.lastDutyEndDateKey, st.lastDutyEndMin, day.dateKey, task.startMin);
        return gap >= conditions.restHours * 60;
      });

      // Policy: trip (and sweep) tasks are filled before reserve tasks whenever the day's
      // driver pool runs short -- "make priority to the trip tasks... a reserve task can have
      // no driver assigned... make sure the trip task always filled." Processing every
      // non-reserve task first, reserve tasks last, is what makes a scarce driver pool exhaust
      // itself on reserve tasks rather than on trips. Only the processing order changes here --
      // day.tasks itself (and its row/col patch targets) is untouched.
      const orderedTasks = day.tasks.filter((t) => t.kind !== "reserve").concat(spreadReserveTasks(day.tasks.filter((t) => t.kind === "reserve")));

      orderedTasks.forEach((task) => {
        const shiftIdx = classifyShiftForMinutes(conditions, task.startMin);
        const inShift = (byShift[shiftIdx] || []).filter((d) => !usedDriverIds.has(d.id));

        // Hard rule: never violated, even if it leaves this task unfilled -- see the rest-time
        // condition this mirrors.
        let restOk = restFilter(inShift, task);

        // Soft shift-bucket matching must never be the reason a task goes unfilled while an
        // available driver exists -- a task whose start time falls outside every configured
        // shift window (e.g. a task starting before the earliest shift's window opens) would
        // otherwise be permanently unassignable no matter how many drivers are free that day.
        // Falling back to every remaining available driver (still hard-filtered by rest-time)
        // keeps the rest-time rule absolute while making the shift match itself a preference.
        let usedFallback = false;
        if (!restOk.length) {
          const stillAvailable = available.filter((d) => !usedDriverIds.has(d.id));
          restOk = restFilter(stillAvailable, task);
          usedFallback = true;
        }
        if (!restOk.length) { unassignedTasks.push(task); return; }

        const wantKind = task.kind === "reserve" ? "reserve" : "trip";

        // A candidate is "fairness compliant" for this task if picking them wouldn't push them
        // over their OWN shift-peer group's ratio ceiling AND wouldn't repeat their immediately
        // previous kind -- the two rules are applied together so the same adjacent-shift borrow
        // below can rescue either one, instead of each rule needing its own separate widening
        // logic. Each candidate is judged against their own group (driverShiftIdx[d.id]), not
        // the task's shift -- a borrowed candidate from another shift still owes fairness to
        // their own peers, not the task's.
        const isFairnessCompliant = (d) => !isOverKindQuota(state[d.id], groupReserveFrac(driverShiftIdx[d.id]), wantKind) && !isRepeatingLastKind(state[d.id], wantKind);
        let fairOk = restOk.filter(isFairnessCompliant);

        // If literally everyone left in THIS shift's own locked-in bucket already breaks a
        // fairness rule (over quota for this kind, or would repeat their last kind), there's
        // nobody in it to pick fairly today. Rather than give up on fairness, borrow from the
        // immediately adjacent shift(s) in the fixed rotation order only (Early Morning <-> Late
        // Morning, Early Afternoon <-> Late Afternoon, Late Afternoon <-> Night, never further)
        // -- "so there's not a lot of gap between shift." Not attempted once the shift match has
        // already been abandoned entirely (usedFallback), since that's already drawing from
        // every shift.
        if (!fairOk.length && !usedFallback && shiftIdx != null) {
          const adjacentPool = [shiftIdx - 1, shiftIdx + 1]
            .filter((i) => i >= 0 && i < cycleLen)
            .flatMap((i) => byShift[i] || [])
            .filter((d) => !usedDriverIds.has(d.id));
          const adjacentFairOk = restFilter(adjacentPool, task).filter(isFairnessCompliant);
          if (adjacentFairOk.length) {
            restOk = adjacentFairOk;
            fairOk = adjacentFairOk;
            usedFallback = true; // reuse the shift-closeness tiebreak sort below for this borrowed pool
          } else {
            // Even the neighboring shift has nobody fairness-compliant left. This is what actually
            // happens when a shift bucket is structurally short on trip (or reserve) supply for a
            // long stretch -- confirmed directly against a real month's output: some drivers ended
            // up at 13 reserve/3 trip while others sat at 2 reserve/14 trip, the same per-shift
            // supply skew pulling opposite directions, because adjacent-only borrowing had nowhere
            // left to draw from on THIS shift's own persistently short side. Widening one more
            // step -- every available driver, any shift -- is what actually lets a trip-surplus
            // shift correct a reserve-starved one instead of the tolerance cap just giving up.
            // Still fairness-first, and still only a preference: shift-closeness remains the
            // tiebreak below via usedFallback, so this only reaches further when it actually has to.
            const anyPool = available.filter((d) => !usedDriverIds.has(d.id));
            const anyFairOk = restFilter(anyPool, task).filter(isFairnessCompliant);
            if (anyFairOk.length) {
              restOk = anyFairOk;
              fairOk = anyFairOk;
              usedFallback = true;
            }
          }
        }

        if (fairOk.length) restOk = fairOk;

        if (usedFallback) {
          // Among the fallback candidates, still prefer whoever's own locked shift is closest to
          // this task's start time, so the relaxation degrades gracefully rather than picking
          // arbitrarily.
          restOk.sort((a, b) => {
            const scoreA = ratioPreference(state[a.id], groupReserveFrac(driverShiftIdx[a.id]), wantKind) + specialRuleBias(a, task, rules);
            const scoreB = ratioPreference(state[b.id], groupReserveFrac(driverShiftIdx[b.id]), wantKind) + specialRuleBias(b, task, rules);
            const ratioDiff = scoreB - scoreA;
            if (ratioDiff !== 0) return ratioDiff;
            const distA = shiftIdx == null ? 0 : shiftDistance(driverShiftIdx[a.id], shiftIdx, cycleLen);
            const distB = shiftIdx == null ? 0 : shiftDistance(driverShiftIdx[b.id], shiftIdx, cycleLen);
            return distA - distB;
          });
        } else {
          restOk.sort((a, b) => {
            const scoreA = ratioPreference(state[a.id], groupReserveFrac(driverShiftIdx[a.id]), wantKind) + specialRuleBias(a, task, rules);
            const scoreB = ratioPreference(state[b.id], groupReserveFrac(driverShiftIdx[b.id]), wantKind) + specialRuleBias(b, task, rules);
            return scoreB - scoreA;
          });
        }
        const chosen = restOk[0];

        usedDriverIds.add(chosen.id);
        assignments.push({ task, driver: chosen });

        const st = state[chosen.id];
        st.lastDutyEndDateKey = day.dateKey;
        st.lastDutyEndMin = task.endMin != null ? task.endMin : task.startMin;
        st.recentKinds.push(wantKind);
        if (st.recentKinds.length > capLen) st.recentKinds.shift();
        if (wantKind === "reserve") st.cumulativeReserve = (st.cumulativeReserve || 0) + 1;
        else st.cumulativeTrip = (st.cumulativeTrip || 0) + 1;
      });

      // Any driver still available after every real task (trip, sweep, and every reserve slot,
      // including the round-robin-spread duplicates) has been handled gets a manufactured
      // reserve duty for the day -- "if there are unassigned drivers, create a reserve task for
      // them, I don't want to see any unassigned driver." This is a synthetic task with no row
      // in the Task Program (there's no real duty behind it to patch there), so buildPatches()
      // only ever writes it into that driver's own roster day-cell -- the same "RESERVE" label
      // already used elsewhere in these files for a reserve day -- never into the Task Program.
      // Their own locked shift's window stands in for a start/end time, so this reads as a
      // normal reserve day within their rotation rather than a special case, and updates
      // rest-time/ratio state exactly the way a real reserve task would.
      available.filter((d) => !usedDriverIds.has(d.id)).forEach((driver) => {
        const shiftIdx = computeShiftIndexForDriver(state[driver.id], conditions, day.date);
        const shift = conditions.shifts[shiftIdx];
        const startMin = parseHHMM(shift.start);
        const endMin = parseHHMM(shift.end);
        const syntheticTask = { row: null, code: "RESERVE", kind: "reserve", destination: null, startMin, endMin, isPassengerLeg: false, synthetic: true };
        assignments.push({ task: syntheticTask, driver });
        usedDriverIds.add(driver.id);
        const st = state[driver.id];
        st.lastDutyEndDateKey = day.dateKey;
        st.lastDutyEndMin = endMin;
        st.recentKinds.push("reserve");
        if (st.recentKinds.length > capLen) st.recentKinds.shift();
        st.cumulativeReserve = (st.cumulativeReserve || 0) + 1;
      });

      return {
        date: day.date, dateKey: day.dateKey, sheetIndex: day.sheetIndex, nameCol: day.nameCol,
        assignments,
        unassignedTasks,
        unassignedDrivers: available.filter((d) => !usedDriverIds.has(d.id)),
      };
    });
    return { perDay, rotationState: state };
  }

  // Per-driver, per-week breakdown of shift + trip/reserve/sweep counts for a generated run --
  // the reference the supervisor asked for so a following month's Generate can be run with an
  // eye on fairness (whoever got more trips this run can deliberately get more reserve next
  // time). Weeks are plain 7-day blocks starting from the first day actually processed, labeled
  // with real dates rather than trying to replicate calendar week boundaries.
  function buildMonthlySummary(plan, conditions, rotationState) {
    const days = plan.perDay;
    if (!days.length) return { weeks: [], driverSummaries: [] };

    const weeks = [];
    for (let i = 0; i < days.length; i += 7) {
      const chunk = days.slice(i, i + 7);
      weeks.push({ index: weeks.length, startDateKey: chunk[0].dateKey, endDateKey: chunk[chunk.length - 1].dateKey, days: chunk });
    }

    const byDriver = {};
    function ensure(driver) {
      if (!byDriver[driver.id]) {
        byDriver[driver.id] = {
          driver,
          weeks: weeks.map(() => ({ shiftIndexes: new Set(), tripCount: 0, reserveCount: 0, sweepCount: 0 })),
        };
      }
      return byDriver[driver.id];
    }

    weeks.forEach((week, wi) => {
      week.days.forEach((day) => {
        day.assignments.forEach(({ task, driver }) => {
          const wk = ensure(driver).weeks[wi];
          if (task.kind === "reserve") wk.reserveCount++;
          else if (task.kind === "sweep") wk.sweepCount++;
          else wk.tripCount++;
          const st = rotationState[driver.id];
          const shiftIdx = st ? computeShiftIndexForDriver(st, conditions, day.date) : null;
          if (shiftIdx != null) wk.shiftIndexes.add(shiftIdx);
        });
      });
    });

    const driverSummaries = Object.values(byDriver)
      .map((rec) => ({
        driverId: rec.driver.id,
        name: rec.driver.name,
        totalTrips: rec.weeks.reduce((s, w) => s + w.tripCount, 0),
        totalReserve: rec.weeks.reduce((s, w) => s + w.reserveCount, 0),
        totalSweep: rec.weeks.reduce((s, w) => s + w.sweepCount, 0),
        weeks: rec.weeks.map((wk) => ({
          shiftNames: [...wk.shiftIndexes].map((i) => conditions.shifts[i].name),
          tripCount: wk.tripCount,
          reserveCount: wk.reserveCount,
          sweepCount: wk.sweepCount,
        })),
      }))
      .sort((a, b) => a.name.localeCompare(b.name));

    return {
      weeks: weeks.map((w) => ({ index: w.index, startDateKey: w.startDateKey, endDateKey: w.endDateKey })),
      driverSummaries,
    };
  }

  // --- Rotation memory: portable, explicit save/restore of rotationState --------------------
  // Automatically persisting rotationState in the browser (what an earlier version of this tool
  // did) turned out to be dangerous: it silently carried leftover state from testing/experiments
  // into real runs, with no visibility into what was even stored -- confirmed to cause massive,
  // hard-to-diagnose unassigned-task counts (a driver's memorized "last duty end" landing AFTER
  // the new run's start date makes the rest-time gap compute negative, instantly failing that
  // driver out of every task, for almost the entire roster at once).
  // The fix is making memory an explicit, portable file a supervisor grants on purpose (see the
  // "Grant" flow in the HTML) instead of something that accumulates invisibly. These two
  // functions are the pure data half of that: turning rotationState into plain rows a caller can
  // write into a worksheet, and reading those rows back out of an uploaded workbook.

  function minutesToHHMM(min) {
    const h = Math.floor(min / 60), m = min % 60;
    return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
  }

  function monthKeyFromDateKey(dk) {
    return dk.slice(0, 7);
  }

  function monthLabelFromDateKey(dk) {
    const d = new Date(dk + "T00:00:00");
    return d.toLocaleDateString("en-US", { month: "long", year: "numeric" });
  }

  function buildMemoryRows(rosterData, rotationState) {
    const nameById = {};
    rosterData.drivers.forEach((d) => { nameById[d.id] = d.name; });
    return Object.keys(rotationState).map((id) => {
      const st = rotationState[id];
      return {
        driverId: id,
        driverName: nameById[id] || "",
        shiftAnchorDate: st.shiftAnchorDate || null,
        shiftAnchorIndex: st.shiftAnchorIndex != null ? st.shiftAnchorIndex : null,
        lastDutyEndDateKey: st.lastDutyEndDateKey || null,
        lastDutyEndTime: st.lastDutyEndMin != null ? minutesToHHMM(st.lastDutyEndMin) : null,
        recentKinds: (st.recentKinds || []).join(","),
        cumulativeReserve: st.cumulativeReserve || 0,
        cumulativeTrip: st.cumulativeTrip || 0,
      };
    });
  }

  // Reads a memory workbook back into { station, monthLabel, grantedAt, rotationState } --
  // by label, not by fixed row/column numbers, the same way parseRoster/parseTaskProgram locate
  // their own headers, so this isn't brittle against exactly how a caller laid out the metadata
  // rows above the table.
  function parseMemoryWorkbook(workbook) {
    const ws = workbook.worksheets[0];
    if (!ws) throw new Error("This memory file has no worksheet.");

    const idHeaderCell = findHeaderCell(ws, "Driver ID", 20);
    if (!idHeaderCell) throw new Error("This doesn't look like a rotation memory file -- no \"Driver ID\" column found. Was it downloaded from this tool's Grant button?");
    const anchorDateCell = findHeaderCell(ws, "Shift Anchor Date", 20);
    const anchorIdxCell = findHeaderCell(ws, "Shift Anchor Index", 20);
    const lastEndDateCell = findHeaderCell(ws, "Last Duty End Date", 20);
    const lastEndTimeCell = findHeaderCell(ws, "Last Duty End Time", 20);
    const recentKindsCell = findHeaderCell(ws, "Recent Kinds", 20);
    if (!anchorDateCell || !anchorIdxCell || !lastEndDateCell || !lastEndTimeCell || !recentKindsCell) {
      throw new Error("This memory file is missing one or more expected columns -- was it downloaded from this tool's Grant button?");
    }
    // Added later than the other columns -- optional so an older memory file (granted before
    // cumulative fairness tracking existed) still loads, just starting cumulative counts at 0
    // rather than failing to load altogether.
    const cumReserveCell = findHeaderCell(ws, "Cumulative Reserve", 20);
    const cumTripCell = findHeaderCell(ws, "Cumulative Trip", 20);

    const readAdjacent = (cell) => {
      if (!cell) return null;
      const v = displayValue(ws.getRow(cell.row).getCell(cell.col + 1));
      if (v == null || v === "") return null;
      return v instanceof Date ? v.toISOString() : String(v).trim();
    };
    const station = readAdjacent(findHeaderCell(ws, "Station", 10));
    const monthLabel = readAdjacent(findHeaderCell(ws, "Granted for", 10));
    const grantedAt = readAdjacent(findHeaderCell(ws, "Granted at", 10));

    const headerRow = idHeaderCell.row;
    const idCol = idHeaderCell.col;
    const rotationState = {};
    for (let r = headerRow + 1; r <= ws.rowCount; r++) {
      const row = ws.getRow(r);
      const idVal = displayValue(row.getCell(idCol));
      if (idVal == null || String(idVal).trim() === "") continue;
      const id = String(idVal).trim();
      const anchorDateVal = displayValue(row.getCell(anchorDateCell.col));
      const anchorIdxVal = displayValue(row.getCell(anchorIdxCell.col));
      const lastEndDateVal = displayValue(row.getCell(lastEndDateCell.col));
      const lastEndTimeVal = displayValue(row.getCell(lastEndTimeCell.col));
      const recentKindsVal = displayValue(row.getCell(recentKindsCell.col));
      const cumReserveVal = cumReserveCell ? displayValue(row.getCell(cumReserveCell.col)) : null;
      const cumTripVal = cumTripCell ? displayValue(row.getCell(cumTripCell.col)) : null;
      rotationState[id] = {
        shiftAnchorDate: anchorDateVal != null && anchorDateVal !== "" ? String(anchorDateVal).trim() : null,
        shiftAnchorIndex: anchorIdxVal != null && anchorIdxVal !== "" ? parseInt(anchorIdxVal, 10) : null,
        lastDutyEndDateKey: lastEndDateVal != null && lastEndDateVal !== "" ? String(lastEndDateVal).trim() : null,
        lastDutyEndMin: lastEndTimeVal != null && lastEndTimeVal !== "" ? parseHHMM(String(lastEndTimeVal).trim()) : null,
        recentKinds: recentKindsVal != null && recentKindsVal !== "" ? String(recentKindsVal).split(",").map((s) => s.trim()).filter(Boolean) : [],
        cumulativeReserve: cumReserveVal != null && cumReserveVal !== "" ? parseInt(cumReserveVal, 10) : 0,
        cumulativeTrip: cumTripVal != null && cumTripVal !== "" ? parseInt(cumTripVal, 10) : 0,
      };
    }
    if (!Object.keys(rotationState).length) throw new Error("This memory file has no driver rows in it.");

    return { station, monthLabel, grantedAt, rotationState };
  }

  // Converts a plan into plain {row, col, value} patch lists, grouped by sheet index, ready for
  // xlsx_surgical_patch.js's applyCellPatches() -- deliberately NOT an ExcelJS workbook mutation.
  // Earlier versions of this engine wrote assignments directly into a live ExcelJS workbook and
  // asked ExcelJS to serialize the whole file back out, which turned out to be provably lossy in
  // ways that corrupted real output files (dropped external-link formulas left dangling, and a
  // ~460KB drawing part rebuilt as a ~1KB stub that made the file unopenable in real Excel).
  // Producing plain patch data here, with no ExcelJS involvement in the write path at all, is
  // what lets the surgical patcher touch only the exact cells being changed and nothing else.
  // "flag": true patch entries are style-only (no value change) -- xlsx_surgical_patch.js applies
  // a distinct fill color to those cells and leaves their content exactly as-is, marking a driver
  // who was available that day but genuinely had no task left to assign them (every task that
  // day was already filled) so a supervisor can see it at a glance rather than the cell just
  // looking like an ordinary blank/available day.
  // Matches the Task Program's own NAME-column convention when a VLOOKUP resolves successfully
  // (confirmed directly against a real file's resolved output): "<prefix, e.g. 'T- '><ID>-<NAME>"
  // followed immediately by the phone number, no separator -- whatever format the roster's own
  // Phone column happens to have it in.
  function formatDriverForTaskCell(driver) {
    return `${driver.namePrefix || ""}${driver.id}-${driver.name}${driver.phone || ""}`;
  }

  function buildPatches(plan) {
    const rosterPatches = { 0: [] };
    const taskPatches = {};
    plan.perDay.forEach((day) => {
      if (!taskPatches[day.sheetIndex]) taskPatches[day.sheetIndex] = [];
      day.assignments.forEach(({ task, driver }) => {
        if (!task.synthetic) {
          taskPatches[day.sheetIndex].push({ row: task.row, col: day.nameCol, value: formatDriverForTaskCell(driver) });
        }
        rosterPatches[0].push({ row: driver.row, col: driver.colByDateKey[day.dateKey], value: task.code });
      });
      (day.unassignedDrivers || []).forEach((driver) => {
        rosterPatches[0].push({ row: driver.row, col: driver.colByDateKey[day.dateKey], flag: true });
      });
    });
    return { rosterPatches, taskPatches };
  }

  return {
    dateKey, addDays, isAvailable, classifyCode, classifyDestination,
    parseRoster, parseTaskProgram, assignSimple, buildPatches,
    SHIFT_NAMES, defaultConditions, parseHHMM, conditionsAreComplete,
    classifyShiftForMinutes, computeShiftIndexForDriver, assignWithConditions,
    buildMonthlySummary,
    minutesToHHMM, monthKeyFromDateKey, monthLabelFromDateKey,
    buildMemoryRows, parseMemoryWorkbook, formatDriverForTaskCell, spreadReserveTasks,
    isOverKindQuota, isRepeatingLastKind,
  };
});
