/*
 * Cross-checks the JS reserve-duty port against order_b_engine/reserve.py's exact output for
 * a fixed list of leftover drivers, the same way joint_scheduler.test.js cross-checks against
 * joint_demo.py. Expected values below were generated by running the Python function directly
 * (see the shell command in the PR/commit history) -- update both sides together if the shift
 * defaults ever change.
 *
 * Run with: node web/reserve.test.js
 */
const ReserveBuilder = require("./reserve.js");

function assert(cond, msg) {
  if (!cond) throw new Error("FAIL: " + msg);
}

const drivers = Array.from({ length: 10 }, (_, i) => ({ id: String(i + 1), name: `Driver ${i + 1}` }));
const duties = ReserveBuilder.buildReserveDuties(drivers);

assert(duties.length === 10, `expected 10 duties, got ${duties.length}`);

// Python: day_start=6:00, day_end=22:00, shift_interval_hours=3 -> shift_starts at
// 06:00, 09:00, 12:00, 15:00, 18:00, 21:00 (6 shifts); drivers_per_shift=4 -> driver i uses
// shift_starts[(i // 4) % 6].
const expectedTaskCodes = [
  "0600/7R", "0600/7R", "0600/7R", "0600/7R", // i=0..3 -> shift 0 (06:00)
  "0900/7R", "0900/7R", "0900/7R", "0900/7R", // i=4..7 -> shift 1 (09:00)
  "1200/7R", "1200/7R",                       // i=8..9 -> shift 2 (12:00)
];
duties.forEach((d, i) => {
  assert(d.taskCode === expectedTaskCodes[i], `duty ${i}: expected ${expectedTaskCodes[i]}, got ${d.taskCode}`);
  assert(d.isReserve === true, `duty ${i}: expected isReserve=true`);
  assert(d.dutyMin === 420, `duty ${i}: expected 7h (420min) duty, got ${d.dutyMin}`);
  assert(d.legs.length === 0, `duty ${i}: reserve duties should have no legs`);
});

// Sign-out = sign-in + 7h, same-day (no wraparound needed for these shift times).
assert(duties[0].signIn === 6 * 60 && duties[0].signOut === 13 * 60, "shift 0 sign-in/out mismatch");
assert(duties[8].signIn === 12 * 60 && duties[8].signOut === 19 * 60, "shift 2 sign-in/out mismatch");

assert(ReserveBuilder.buildReserveDuties([]).length === 0, "empty driver list should yield no duties");

console.log(`PASS: ${duties.length} reserve duties match the Python reserve.py shift assignment exactly.`);
